App:
  environment: staging
  serviceName: king

Ports:
  grpc: 5000
  http: 8007
  https: 8003
  metric: 9097

Server:
  timeout: 5s

DB:
  max_open_cons: 5
  max_idle_cons: 1

Telemetry:
  collector_enable: false
  collector_debug: false
  collector_grpc_addr: 192.168.1.122:4317
