// Package adapters are the glue between components and external sources.
// # This manifest was generated by ymir. DO NOT EDIT.
package adapters

import (
	"fmt"
	"net/http"
	"strings"

	sqlEnt "entgo.io/ent/dialect/sql"
	"github.com/go-resty/resty/v2"
	"github.com/rs/zerolog/log"
	"go.mongodb.org/mongo-driver/mongo"

	"github.com/kubuskotak/king/pkg/persist/crud"
)

type client interface {
	*sqlEnt.Driver | *http.Client | *resty.Client | *mongo.Client
}

// Driver - interface adapter.
type Driver[T client] interface {
	Open() (T, error)
	Connect() error
	Disconnect() error
}

// Adapter components for external sources.
type Adapter struct {
	CrudSQLite   *CrudSQLite
	CrudPostgres *CrudPostgres
	CrudMongoDB *CrudMongoDB
	CrudPersist  *crud.Database
	PokemonResty *resty.Client
}

// Option is Adapter type return func.
type Option func(adapter *Adapter)

// Sync - configure all adapters.
func (a *Adapter) Sync(opts ...Option) {
	for o := range opts {
		opt := opts[o]
		opt(a)
	}
}

// UnSync - release all adapter connection.
func (a *Adapter) UnSync() error {
	var errs []string
	if a.CrudSQLite != nil {
		log.Info().Msg("CrudSQLite is closed")
		if err := a.CrudSQLite.Disconnect(); err != nil {
			errs = append(errs, err.Error())
		}
	}
	if a.CrudPostgres != nil {
		log.Info().Msg("CrudPostgres is closed")
		if err := a.CrudPostgres.Disconnect(); err != nil {
			errs = append(errs, err.Error())
		}
	}
	if a.CrudMongoDB != nil {
		log.Info().Msg("CrudMongoDB is closed")
		if err := a.CrudMongoDB.Disconnect(); err != nil {
			errs = append(errs, err.Error())
		}
	}
	if len(errs) > 0 {
		err := fmt.Errorf(strings.Join(errs, "\n"))
		log.Error().Err(err).Msg("UnSync adapter error")
		return err
	}
	return nil
}
