// Package adapters are the glue between components and external sources.
// # This manifest was generated by ymir. DO NOT EDIT.
package adapters

import (
	"context"
	"testing"

	"github.com/kubuskotak/king/pkg/infrastructure"
	"github.com/stretchr/testify/assert"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

func TestWithCrudMongoDB(t *testing.T) {
	is := assert.New(t)

	ctx := context.Background()
	client, err := mongo.Connect(ctx, options.Client().ApplyURI("mongodb://localhost:27017"))
	if err != nil {
		is.Failf("failed to connect to MongoDB", "%v", err)
	}
	defer client.Disconnect(ctx)

	infrastructure.Configuration(
		infrastructure.WithPath("../.."),
		infrastructure.WithFilename("config.yaml"),
	).Initialize()

	adapter := &Adapter{}
	adapter.Sync(
		WithCrudMongoDB(&CrudMongoDB{
			URI:      "mongodb://localhost:27017",
			Database: "capstone",
		}),
	)

	// Asserts
	is.Nil(adapter.UnSync())
}