// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/application"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/index"
)

// Index is the model entity for the Index schema.
type Index struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IndexQuery when eager-loading is set.
	Edges               IndexEdges `json:"edges"`
	application_indexes *string
	selectValues        sql.SelectValues
}

// IndexEdges holds the relations/edges for other nodes in the graph.
type IndexEdges struct {
	// Application holds the value of the application edge.
	Application *Application `json:"application,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ApplicationOrErr returns the Application value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IndexEdges) ApplicationOrErr() (*Application, error) {
	if e.loadedTypes[0] {
		if e.Application == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: application.Label}
		}
		return e.Application, nil
	}
	return nil, &NotLoadedError{edge: "application"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Index) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case index.FieldID:
			values[i] = new(sql.NullInt64)
		case index.FieldName:
			values[i] = new(sql.NullString)
		case index.ForeignKeys[0]: // application_indexes
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Index fields.
func (i *Index) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case index.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		case index.FieldName:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[j])
			} else if value.Valid {
				i.Name = value.String
			}
		case index.ForeignKeys[0]:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_indexes", values[j])
			} else if value.Valid {
				i.application_indexes = new(string)
				*i.application_indexes = value.String
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Index.
// This includes values selected through modifiers, order, etc.
func (i *Index) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// QueryApplication queries the "application" edge of the Index entity.
func (i *Index) QueryApplication() *ApplicationQuery {
	return NewIndexClient(i.config).QueryApplication(i)
}

// Update returns a builder for updating this Index.
// Note that you need to call Index.Unwrap() before calling this method if this Index
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Index) Update() *IndexUpdateOne {
	return NewIndexClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Index entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Index) Unwrap() *Index {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Index is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Index) String() string {
	var builder strings.Builder
	builder.WriteString("Index(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("name=")
	builder.WriteString(i.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Indexes is a parsable slice of Index.
type Indexes []*Index
