-- Create "articles" table
CREATE TABLE "articles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL DEFAULT '', "body" character varying NOT NULL DEFAULT '', "description" character varying NOT NULL DEFAULT '', "slug" character varying NOT NULL, "user_id" bigint NULL, PRIMARY KEY ("id"));
-- Create index "articles_slug_key" to table: "articles"
CREATE UNIQUE INDEX "articles_slug_key" ON "articles" ("slug");
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "email" character varying NOT NULL, "password" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create "ymirs" table
CREATE TABLE "ymirs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "version" character varying NOT NULL DEFAULT 'alpha-test-dev1', PRIMARY KEY ("id"));
-- Create "applications" table
CREATE TABLE "applications" ("id" character varying NOT NULL, "name" character varying NOT NULL, "apikey" character varying NOT NULL, "user_applications" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "applications_users_applications" FOREIGN KEY ("user_applications") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "applications_apikey_key" to table: "applications"
CREATE UNIQUE INDEX "applications_apikey_key" ON "applications" ("apikey");
-- Create index "applications_name_key" to table: "applications"
CREATE UNIQUE INDEX "applications_name_key" ON "applications" ("name");
-- Create "indexes" table
CREATE TABLE "indexes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "application_indexes" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "indexes_applications_indexes" FOREIGN KEY ("application_indexes") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "indexes_name_key" to table: "indexes"
CREATE UNIQUE INDEX "indexes_name_key" ON "indexes" ("name");
